In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("STUDENT PERFORMANCE.CSV")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   math score       29 non-null     float64
 1   reading score    29 non-null     float64
 2   writing score    29 non-null     float64
 3   placement score  32 non-null     float64
 4   club join year   29 non-null     float64
 5   placement offer  29 non-null     float64
dtypes: float64(6)
memory usage: 1.8 KB

In [3]:
df.fillna(13)

,math score,reading score,writing score,placement score,club join year,placement offer
0,63.0,94.0,79.0,91.0,2021.0,3.0
1,65.0,87.0,75.0,78.0,2020.0,2.0
2,70.0,90.0,67.0,87.0,2021.0,3.0
3,77.0,90.0,69.0,99.0,2021.0,3.0
4,63.0,78.0,61.0,98.0,2019.0,3.0
5,73.0,76.0,66.0,92.0,2018.0,3.0
6,71.0,85.0,67.0,75.0,2020.0,2.0
7,74.0,83.0,78.0,81.0,2021.0,2.0
8,72.0,87.0,64.0,86.0,2021.0,3.0
9,68.0,81.0,62.0,86.0,2019.0,3.0
10,80.0,82.0,71.0,93.0,2018.0,3.0
11,63.0,81.0,62.0,83.0,2020.0,2.0
12,62.0,90.0,60.0,96.0,2021.0,3.0
13,80.0,88.0,62.0,89.0,2019.0,3.0
14,73.0,78.0,67.0,98.0,2020.0,3.0
15,69.0,76.0,62.0,97.0,2018.0,3.0
16,78.0,94.0,67.0,96.0,2020.0,3.0
17,80.0,83.0,71.0,82.0,2021.0,2.0
18,79.0,79.0,69.0,89.0,2020.0,3.0
19,80.0,87.0,80.0,97.0,2020.0,3.0
20,71.0,82.0,61.0,98.0,2018.0,3.0
21,75.0,89.0,65.0,97.0,2020.0,3.0
22,74.0,93.0,71.0,83.0,2020.0,2.0
23,69.0,79.0,77.0,84.0,2020.0,2.0
24,80.0,83.0,80.0,100.0,2019.0,3.0
25,77.0,85.0,69.0,89.0,2020.0,3.0
26,74.0,93.0,68.0,81.0,2021.0,2.0
27,64.0,83.0,64.0,86.0,2018.0,3.0
28,70.0,82.0,75.0,99.0,2019.0,3.0
29,13.0,13.0,13.0,13.0,13.0,13.0
30,13.0,13.0,13.0,13.0,13.0,13.0
31,13.0,13.0,13.0,13.0,13.0,13.0
32,13.0,13.0,13.0,13.0,13.0,13.0
33,13.0,13.0,13.0,13.0,13.0,13.0
34,13.0,13.0,13.0,94.0,13.0,13.0
35,13.0,13.0,13.0,95.0,13.0,13.0
36,13.0,13.0,13.0,92.0,13.0,13.0

In [4]:
df.min

<bound method DataFrame.min of     math score  reading score  writing score  placement score  club join year  \
0         63.0           94.0           79.0             91.0          2021.0
1         65.0           87.0           75.0             78.0          2020.0
2         70.0           90.0           67.0             87.0          2021.0
3         77.0           90.0           69.0             99.0          2021.0
4         63.0           78.0           61.0             98.0          2019.0
5         73.0           76.0           66.0             92.0          2018.0
6         71.0           85.0           67.0             75.0          2020.0
7         74.0           83.0           78.0             81.0          2021.0
8         72.0           87.0           64.0             86.0          2021.0
9         68.0           81.0           62.0             86.0          2019.0
10        80.0           82.0           71.0             93.0          2018.0
11        63.0           81.0           62.0             83.0          2020.0
12        62.0           90.0           60.0             96.0          2021.0
13        80.0           88.0           62.0             89.0          2019.0
14        73.0           78.0           67.0             98.0          2020.0
15        69.0           76.0           62.0             97.0          2018.0
16        78.0           94.0           67.0             96.0          2020.0
17        80.0           83.0           71.0             82.0          2021.0
18        79.0           79.0           69.0             89.0          2020.0
19        80.0           87.0           80.0             97.0          2020.0
20        71.0           82.0           61.0             98.0          2018.0
21        75.0           89.0           65.0             97.0          2020.0
22        74.0           93.0           71.0             83.0          2020.0
23        69.0           79.0           77.0             84.0          2020.0
24        80.0           83.0           80.0            100.0          2019.0
25        77.0           85.0           69.0             89.0          2020.0
26        74.0           93.0           68.0             81.0          2021.0
27        64.0           83.0           64.0             86.0          2018.0
28        70.0           82.0           75.0             99.0          2019.0
29         NaN            NaN            NaN              NaN             NaN
30         NaN            NaN            NaN              NaN             NaN
31         NaN            NaN            NaN              NaN             NaN
32         NaN            NaN            NaN              NaN             NaN
33         NaN            NaN            NaN              NaN             NaN
34         NaN            NaN            NaN             94.0             NaN
35         NaN            NaN            NaN             95.0             NaN
36         NaN            NaN            NaN             92.0             NaN

    placement offer
0               3.0
1               2.0
2               3.0
3               3.0
4               3.0
5               3.0
6               2.0
7               2.0
8               3.0
9               3.0
10              3.0
11              2.0
12              3.0
13              3.0
14              3.0
15              3.0
16              3.0
17              2.0
18              3.0
19              3.0
20              3.0
21              3.0
22              2.0
23              2.0
24              3.0
25              3.0
26              2.0
27              3.0
28              3.0
29              NaN
30              NaN
31              NaN
32              NaN
33              NaN
34              NaN
35              NaN
36              NaN  >

In [5]:
df.tail(7)

,math score,reading score,writing score,placement score,club join year,placement offer
30,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,94.0,NaN,NaN
35,NaN,NaN,NaN,95.0,NaN,NaN
36,NaN,NaN,NaN,92.0,NaN,NaN

In [6]:
df.tail(8)

,math score,reading score,writing score,placement score,club join year,placement offer
29,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,94.0,NaN,NaN
35,NaN,NaN,NaN,95.0,NaN,NaN
36,NaN,NaN,NaN,92.0,NaN,NaN

In [7]:
df.describe()

,math score,reading score,writing score,placement score,club join year,placement offer
count,29.000000,29.000000,29.000000,32.000000,29.000000,29.000000
mean,72.206897,84.758621,68.586207,90.343750,2019.758621,2.724138
std,5.906288,5.369591,6.161616,6.995895,1.057462,0.454859
min,62.000000,76.000000,60.000000,75.000000,2018.000000,2.000000
25%,69.000000,81.000000,64.000000,85.500000,2019.000000,2.000000
50%,73.000000,83.000000,67.000000,91.500000,2020.000000,3.000000
75%,77.000000,89.000000,71.000000,97.000000,2021.000000,3.000000
max,80.000000,94.000000,80.000000,100.000000,2021.000000,3.000000

In [14]:
df

,math score,reading score,writing score,placement score,club join year,placement offer
0,63.0,94.0,79.0,91.0,2021.0,3.0
1,65.0,87.0,75.0,78.0,2020.0,2.0
2,70.0,90.0,67.0,87.0,2021.0,3.0
3,77.0,90.0,69.0,99.0,2021.0,3.0
4,63.0,78.0,61.0,98.0,2019.0,3.0
5,73.0,76.0,66.0,92.0,2018.0,3.0
6,71.0,85.0,67.0,75.0,2020.0,2.0
7,74.0,83.0,78.0,81.0,2021.0,2.0
8,72.0,87.0,64.0,86.0,2021.0,3.0
9,68.0,81.0,62.0,86.0,2019.0,3.0
10,80.0,82.0,71.0,93.0,2018.0,3.0
11,63.0,81.0,62.0,83.0,2020.0,2.0
12,62.0,90.0,60.0,96.0,2021.0,3.0
13,80.0,88.0,62.0,89.0,2019.0,3.0
14,73.0,78.0,67.0,98.0,2020.0,3.0
15,69.0,76.0,62.0,97.0,2018.0,3.0
16,78.0,94.0,67.0,96.0,2020.0,3.0
17,80.0,83.0,71.0,82.0,2021.0,2.0
18,79.0,79.0,69.0,89.0,2020.0,3.0
19,80.0,87.0,80.0,97.0,2020.0,3.0
20,71.0,82.0,61.0,98.0,2018.0,3.0
21,75.0,89.0,65.0,97.0,2020.0,3.0
22,74.0,93.0,71.0,83.0,2020.0,2.0
23,69.0,79.0,77.0,84.0,2020.0,2.0
24,80.0,83.0,80.0,100.0,2019.0,3.0
25,77.0,85.0,69.0,89.0,2020.0,3.0
26,74.0,93.0,68.0,81.0,2021.0,2.0
27,64.0,83.0,64.0,86.0,2018.0,3.0
28,70.0,82.0,75.0,99.0,2019.0,3.0
29,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,94.0,NaN,NaN
35,NaN,NaN,NaN,95.0,NaN,NaN
36,NaN,NaN,NaN,92.0,NaN,NaN

In [18]:
df.min

<bound method DataFrame.min of     math score  reading score  writing score  placement score  club join year  \
0         63.0           94.0           79.0             91.0          2021.0
1         65.0           87.0           75.0             78.0          2020.0
2         70.0           90.0           67.0             87.0          2021.0
3         77.0           90.0           69.0             99.0          2021.0
4         63.0           78.0           61.0             98.0          2019.0
5         73.0           76.0           66.0             92.0          2018.0
6         71.0           85.0           67.0             75.0          2020.0
7         74.0           83.0           78.0             81.0          2021.0
8         72.0           87.0           64.0             86.0          2021.0
9         68.0           81.0           62.0             86.0          2019.0
10        80.0           82.0           71.0             93.0          2018.0
11        63.0           81.0           62.0             83.0          2020.0
12        62.0           90.0           60.0             96.0          2021.0
13        80.0           88.0           62.0             89.0          2019.0
14        73.0           78.0           67.0             98.0          2020.0
15        69.0           76.0           62.0             97.0          2018.0
16        78.0           94.0           67.0             96.0          2020.0
17        80.0           83.0           71.0             82.0          2021.0
18        79.0           79.0           69.0             89.0          2020.0
19        80.0           87.0           80.0             97.0          2020.0
20        71.0           82.0           61.0             98.0          2018.0
21        75.0           89.0           65.0             97.0          2020.0
22        74.0           93.0           71.0             83.0          2020.0
23        69.0           79.0           77.0             84.0          2020.0
24        80.0           83.0           80.0            100.0          2019.0
25        77.0           85.0           69.0             89.0          2020.0
26        74.0           93.0           68.0             81.0          2021.0
27        64.0           83.0           64.0             86.0          2018.0
28        70.0           82.0           75.0             99.0          2019.0
29         NaN            NaN            NaN              NaN             NaN
30         NaN            NaN            NaN              NaN             NaN
31         NaN            NaN            NaN              NaN             NaN
32         NaN            NaN            NaN              NaN             NaN
33         NaN            NaN            NaN              NaN             NaN
34         NaN            NaN            NaN             94.0             NaN
35         NaN            NaN            NaN             95.0             NaN
36         NaN            NaN            NaN             92.0             NaN

    placement offer
0               3.0
1               2.0
2               3.0
3               3.0
4               3.0
5               3.0
6               2.0
7               2.0
8               3.0
9               3.0
10              3.0
11              2.0
12              3.0
13              3.0
14              3.0
15              3.0
16              3.0
17              2.0
18              3.0
19              3.0
20              3.0
21              3.0
22              2.0
23              2.0
24              3.0
25              3.0
26              2.0
27              3.0
28              3.0
29              NaN
30              NaN
31              NaN
32              NaN
33              NaN
34              NaN
35              NaN
36              NaN  >

In [23]:
df.columns.values

array(['math score', 'reading score', 'writing score', 'placement score',
       'club join year', 'placement offer'], dtype=object)

In [24]:
df.iloc[20]

math score           71.0
reading score        82.0
writing score        61.0
placement score      98.0
club join year     2018.0
placement offer       3.0
Name: 20, dtype: float64

In [25]:
df.iloc[:,1:4]

    reading score  writing score  placement score
0            94.0           79.0             91.0
1            87.0           75.0             78.0
2            90.0           67.0             87.0
3            90.0           69.0             99.0
4            78.0           61.0             98.0
5            76.0           66.0             92.0
6            85.0           67.0             75.0
7            83.0           78.0             81.0
8            87.0           64.0             86.0
9            81.0           62.0             86.0
10           82.0           71.0             93.0
11           81.0           62.0             83.0
12           90.0           60.0             96.0
13           88.0           62.0             89.0
14           78.0           67.0             98.0
15           76.0           62.0             97.0
16           94.0           67.0             96.0
17           83.0           71.0             82.0
18           79.0           69.0             89.0
19           87.0           80.0             97.0
20           82.0           61.0             98.0
21           89.0           65.0             97.0
22           93.0           71.0             83.0
23           79.0           77.0             84.0
24           83.0           80.0            100.0
25           85.0           69.0             89.0
26           93.0           68.0             81.0
27           83.0           64.0             86.0
28           82.0           75.0             99.0
29            NaN            NaN              NaN
30            NaN            NaN              NaN
31            NaN            NaN              NaN
32            NaN            NaN              NaN
33            NaN            NaN              NaN
34            NaN            NaN             94.0
35            NaN            NaN             95.0
36            NaN            NaN             92.0

In [32]:
df.math score.fillna(67)

<class 'SyntaxError'>: invalid syntax (<ipython-input-32-def8d71ad330>, line 1)